name: Python CI/CD

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'


    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-html flake8

    - name: Run tests with coverage
      run: |
        pytest --html=pytest_report.html --self-contained-html

    - name: Upload test report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: pytest-report-${{ matrix.python-version }}
        path: pytest_report.html

    - name: PEP8 Compliance Check
      run: |
        # Critical errors that fail the build
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        
        # Style warnings (shown but don't fail)
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics